ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS descricao_ativo TEXT,
  ADD COLUMN IF NOT EXISTS lista TEXT,
  ADD COLUMN IF NOT EXISTS qtd NUMERIC,
  ADD COLUMN IF NOT EXISTS vlr_compra NUMERIC,
  ADD COLUMN IF NOT EXISTS custo_sem_antecip NUMERIC,
  ADD COLUMN IF NOT EXISTS custo_com_antecip NUMERIC,
  ADD COLUMN IF NOT EXISTS fornecedor TEXT,
  ADD COLUMN IF NOT EXISTS nota_fiscal TEXT,
  ADD COLUMN IF NOT EXISTS sugestao_cadastro TEXT,
  ADD COLUMN IF NOT EXISTS vlr_mercado NUMERIC,
  ADD COLUMN IF NOT EXISTS fornecedor_01 TEXT;